services:
  otel-lgtm:
    image: grafana/otel-lgtm:latest
    container_name: otel-lgtm
    ports:
      - "3000:3000"   # Grafana UI
      - "4317:4317"   # OTLP gRPC (metrics, traces ingestion)
      - "4318:4318"   # OTLP HTTP (alternative ingestion)
      - "3100:3100"   # Loki (logs backend)
      - "3200:3200"   # Tempo (tracing backend)
      - "9009:9009"   # Mimir (metrics backend)
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - -config.file=/etc/mimir-config.yaml
    volumes:
      - ./mimir-config.yaml:/etc/mimir-config.yaml
    restart: always
